
min_read_qual: 10
min_read_len: 2000
max_read_len: 10000
headcrop: 40
tailcrop: 40
mindepth: 20
min_variant_qual: 10

# More standardised config keys
minlen: 2000
maxlen: 10000

fastplong_cut_tail_window_size: 10
fastplong_cut_tail_mean_quality: 1
fastplong_trim_front: 20
fastplong_trim_tail: 20

msf_trimmer_wf: msf_trimmer_fastplong.smk
trimmer_wf: ngs_pipeline::trimmer/fastplong.smk

# this is targeted non-panel variant calling
mapper_wf: ngs_pipeline::mapper/minimap2_lr.smk
varcaller_wf: ngs_pipeline::varcaller/clair3.smk
jointvarcaller_wf: ngs_pipeline::jointvarcaller/glnexus.smk
minimap2_extra_flags: --MD
# to satisfy global_params.smk
read_length: -1
platform: ONT
instrument: ONT
libprep: ONT

refseq_file: configs/refs/X.fasta
refmap_file: configs/refs/X.fasta.ont.mmi
target_regions: configs/refs/g6pd-regions.bed
interval_dir: configs/refs/range_regions
#amplicon_bed: configs/refs/g6pd_amplicons.bed

variant_info: configs/refs/g6pd_variants_260909.tsv
target_variants: configs/refs/g6pd_variants_260909.bed
target_variants_vcf: configs/refs/g6pd_variants_260909.vcf.gz
phase_info: configs/refs/multiple_missenses.bed
input_allele_only: False
keep_final_bam: True
regions:
  - X

# for amplicon sequencing
deduplicate: False

# for clair3
clair3_extra_flags: --print_ref_calls --base_err=0.05 --snp_min_af=0.0 --indel_min_af=0.0 --var_pct_full=1 --ref_pct_full=1 --var_pct_phasing=1
clair3_mindepth: 10
clair3_minaltdepth: 5
clair3_minaltfreq: 0.25

# for freebayes, adjust this for het call assignment
freebayes_extra_flags: --min-alternate-count 5 --min-alternate-fraction 0.25 --report-monomorphic --use-best-n-alleles 2 -p 2 --limit-coverage 500
freebayes_haplotype_length: -1

# no filter
read_filters: " " 
